### ISSUE TITLE
Compilation fail on OSX

### ISSUE THREAD

**Issue by yugotra** [blackruffy/jroot#1]
System:
OSX 10.11.3
Java jdk1.8.0_45.jdk
gcc Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
Thread model: posix
ROOT 5.34/30
Error:
[ERROR] Unexpected type: 'Bool_t (_)(const TGraph_, Int_t, Int_t)', which is not in imps and excludeTypes or 'Bool_t (_)(const TGraph_, Int_t, Int_t)' is not in cTypes
  at convCType()
  at convArgTypes
  at void TGraph::Sort(Bool_t (_)(const TGraph_, Int_t, Int_t), Bool_t, Int_t, Int_t)
  at main()

**Comment by blackruffy** [comment]
ROOT 5 is not support any more.
Please use ROOT 6.04/14.

**Comment by yugotra** [comment]
Thank you, compilation succeeded on the following system (additional tweak needed to locate jni_md.h)
System:
OSX 10.11.3
Java jdk1.8.0_45.jdk
gcc Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
Thread model: posix
ROOT 6.05/02
Command Line Tools OS X 10.11 for Xcode 7.2

Missing include is in /library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/include/darwin/jni_md.h
Error:
g++ -w -fPIC -Xlinker -rpath -Xlinker `root-config --prefix`/lib -c -o net_blackruffy_root_JRootNative.o net_blackruffy_root_JRootNative.cpp -I./ -I/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/include `root-config --cflags`
In file included from net_blackruffy_root_JRootNative.cpp:1:
In file included from ./net_blackruffy_root_JRootNative.h:2:
/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/include/jni.h:45:10: fatal error: 'jni_md.h' file not found
#include "jni_md.h"
